import { ThemeVariant, PromptTemplate } from './types';

export const FLOWER_THEMES: ThemeVariant[] = [
  { id: 'sakura', labelEN: 'Sakura', labelZH: '櫻花', primary: '#ec4899', secondary: '#fbcfe8', accent: '#db2777', backgroundLight: '#fff1f2', backgroundDark: '#831843', surfaceLight: '#ffffff', surfaceDark: '#500724' },
  { id: 'lotus', labelEN: 'Lotus', labelZH: '蓮花', primary: '#10b981', secondary: '#d1fae5', accent: '#059669', backgroundLight: '#ecfdf5', backgroundDark: '#064e3b', surfaceLight: '#ffffff', surfaceDark: '#022c22' },
  { id: 'peony', labelEN: 'Peony', labelZH: '牡丹', primary: '#e11d48', secondary: '#ffe4e6', accent: '#be123c', backgroundLight: '#fff1f2', backgroundDark: '#881337', surfaceLight: '#ffffff', surfaceDark: '#4c0519' },
  { id: 'orchid', labelEN: 'Orchid', labelZH: '蘭花', primary: '#9333ea', secondary: '#f3e8ff', accent: '#7e22ce', backgroundLight: '#faf5ff', backgroundDark: '#581c87', surfaceLight: '#ffffff', surfaceDark: '#3b0764' },
  { id: 'sunflower', labelEN: 'Sunflower', labelZH: '向日葵', primary: '#eab308', secondary: '#fef9c3', accent: '#ca8a04', backgroundLight: '#fefce8', backgroundDark: '#713f12', surfaceLight: '#ffffff', surfaceDark: '#422006' },
  { id: 'hydrangea', labelEN: 'Hydrangea', labelZH: '繡球花', primary: '#3b82f6', secondary: '#dbeafe', accent: '#2563eb', backgroundLight: '#eff6ff', backgroundDark: '#1e3a8a', surfaceLight: '#ffffff', surfaceDark: '#172554' },
  { id: 'rose', labelEN: 'Rose', labelZH: '玫瑰', primary: '#ef4444', secondary: '#fee2e2', accent: '#dc2626', backgroundLight: '#fef2f2', backgroundDark: '#7f1d1d', surfaceLight: '#ffffff', surfaceDark: '#450a0a' },
  { id: 'lavender', labelEN: 'Lavender', labelZH: '薰衣草', primary: '#8b5cf6', secondary: '#ede9fe', accent: '#7c3aed', backgroundLight: '#f5f3ff', backgroundDark: '#4c1d95', surfaceLight: '#ffffff', surfaceDark: '#2e1065' },
  { id: 'chrysanthemum', labelEN: 'Chrysanthemum', labelZH: '菊花', primary: '#f59e0b', secondary: '#fef3c7', accent: '#d97706', backgroundLight: '#fffbeb', backgroundDark: '#78350f', surfaceLight: '#ffffff', surfaceDark: '#451a03' },
  { id: 'camellia', labelEN: 'Camellia', labelZH: '山茶花', primary: '#f43f5e', secondary: '#ffe4e6', accent: '#e11d48', backgroundLight: '#fff1f2', backgroundDark: '#881337', surfaceLight: '#ffffff', surfaceDark: '#4c0519' },
  { id: 'jasmine', labelEN: 'Jasmine', labelZH: '茉莉', primary: '#14b8a6', secondary: '#ccfbf1', accent: '#0d9488', backgroundLight: '#f0fdfa', backgroundDark: '#134e4a', surfaceLight: '#ffffff', surfaceDark: '#042f2e' },
  { id: 'wisteria', labelEN: 'Wisteria', labelZH: '紫藤', primary: '#a855f7', secondary: '#f3e8ff', accent: '#9333ea', backgroundLight: '#faf5ff', backgroundDark: '#581c87', surfaceLight: '#ffffff', surfaceDark: '#3b0764' },
  { id: 'tulip', labelEN: 'Tulip', labelZH: '鬱金香', primary: '#f97316', secondary: '#ffedd5', accent: '#ea580c', backgroundLight: '#fff7ed', backgroundDark: '#7c2d12', surfaceLight: '#ffffff', surfaceDark: '#431407' },
  { id: 'iris', labelEN: 'Iris', labelZH: '鳶尾花', primary: '#6366f1', secondary: '#e0e7ff', accent: '#4f46e5', backgroundLight: '#eef2ff', backgroundDark: '#312e81', surfaceLight: '#ffffff', surfaceDark: '#1e1b4b' },
  { id: 'daffodil', labelEN: 'Daffodil', labelZH: '水仙', primary: '#fbbf24', secondary: '#fef3c7', accent: '#d97706', backgroundLight: '#fffbeb', backgroundDark: '#78350f', surfaceLight: '#ffffff', surfaceDark: '#451a03' },
  { id: 'poppy', labelEN: 'Poppy', labelZH: '罌粟', primary: '#ef4444', secondary: '#fee2e2', accent: '#b91c1c', backgroundLight: '#fef2f2', backgroundDark: '#7f1d1d', surfaceLight: '#ffffff', surfaceDark: '#450a0a' },
  { id: 'magnolia', labelEN: 'Magnolia', labelZH: '木蘭', primary: '#84cc16', secondary: '#ecfccb', accent: '#65a30d', backgroundLight: '#f7fee7', backgroundDark: '#3f6212', surfaceLight: '#ffffff', surfaceDark: '#1a2e05' },
  { id: 'azalea', labelEN: 'Azalea', labelZH: '杜鵑', primary: '#ec4899', secondary: '#fbcfe8', accent: '#db2777', backgroundLight: '#fff1f2', backgroundDark: '#831843', surfaceLight: '#ffffff', surfaceDark: '#500724' },
  { id: 'plum_blossom', labelEN: 'Plum Blossom', labelZH: '梅花', primary: '#be123c', secondary: '#ffe4e6', accent: '#9f1239', backgroundLight: '#fff1f2', backgroundDark: '#881337', surfaceLight: '#ffffff', surfaceDark: '#4c0519' },
  { id: 'lotus_night', labelEN: 'Lotus Night', labelZH: '夜蓮', primary: '#2dd4bf', secondary: '#ccfbf1', accent: '#14b8a6', backgroundLight: '#0f172a', backgroundDark: '#020617', surfaceLight: '#1e293b', surfaceDark: '#0f172a' },
];

export const PROMPT_TEMPLATES: PromptTemplate[] = [
  { id: 'custom', label: 'Custom / Default', systemPrompt: 'You are a helpful AI assistant.' },
  { id: 'daily', label: 'Daily Assistant', systemPrompt: 'You are my daily executive assistant. Help me organize my schedule, prioritize tasks, and keep responses concise and actionable.' },
  { id: 'pmpt_69A', label: 'pmpt_69A (Reasoning)', systemPrompt: 'You are a deep reasoning engine. Break down complex problems into step-by-step logical components. Show your work.' },
  { id: 'pmpt_69B', label: 'pmpt_69B (Creative)', systemPrompt: 'You are a creative muse. Focus on lateral thinking, novel ideas, and artistic flair. Avoid clichés.' },
];

export const I18N = {
  en: {
    title: "FlowerMind",
    agentsConsole: "Agents Console",
    attachmentChat: "Attachment Chat",
    notesStudio: "Notes Studio",
    dashboard: "Dashboard",
    runAgent: "Run Agent",
    askAttachment: "Ask Attachment",
    transformMarkdown: "Transform to Markdown",
    improveFormat: "Improve Formatting",
    inputPlaceholder: "Type your message...",
    systemPrompt: "System Prompt",
    upload: "Upload File",
    keywords: "Keywords (comma separated)",
    theme: "Theme",
    language: "Language",
    apiKeyNeeded: "API Key Required",
    apiKeyDesc: "Please enter your Gemini API Key. It is stored locally in your browser.",
    save: "Save",
  },
  zhTW: {
    title: "花心智",
    agentsConsole: "智能代理主控台",
    attachmentChat: "附件對話",
    notesStudio: "筆記工作室",
    dashboard: "儀表板",
    runAgent: "執行代理",
    askAttachment: "詢問附件",
    transformMarkdown: "轉換為 Markdown",
    improveFormat: "優化格式",
    inputPlaceholder: "輸入您的訊息...",
    systemPrompt: "系統提示詞",
    upload: "上傳檔案",
    keywords: "關鍵字 (用逗號分隔)",
    theme: "主題",
    language: "語言",
    apiKeyNeeded: "需要 API 金鑰",
    apiKeyDesc: "請輸入您的 Gemini API 金鑰。它將儲存在您的瀏覽器中。",
    save: "儲存",
  }
};